version: '3.8'
services:
  nextjs:
    build: ./nextjs
    ports:
      - "3000:3000"
    volumes:
      - ./nextjs:/app
    command: npm run dev

  nestjs:
    build: ./nestjs
    ports:
      - "3001:3001"
    volumes:
      - ./nestjs:/app
    command: npm run start:dev
